---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8snginxappsot
  namespace: fluxcdtutorial
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sharmaprajesh/k8s_nginxapp_sot.git
