name: ENV Variables
on: push
env:
  WF_ENV: ${{ secrets.WF_ENV }}

jobs:
  log-env:
    env:
      JOB_ENV: Only avaliable to log-env-jobs
    runs-on: ubuntu-latest
    steps:
    - name: Log Env Variables
      env:
        STP_ENV: Only avaliable to Log Env Variables steps
      run: |
        echo "WF_ENV: ${WF_ENV}" 
        echo "JOB_ENV: ${JOB_ENV}" 
        echo "STP_ENV: ${STP_ENV}" 
        
    - name: Log Env Variables 2      
      run: |
        echo "WF_ENV: ${WF_ENV}" 
        echo "JOB_ENV: ${JOB_ENV}" 
        echo "STP_ENV: ${STP_ENV}" 
  
  log-default-env:
    runs-on: ubuntu-latest
    steps:
    - name: Default env variables
      run: |
        echo "HOME: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTION: ${GITHUB_ACTION}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "WF_ENV: ${WF_ENV}" 
        echo "JOB_ENV: ${JOB_ENV}" 
        echo "STP_ENV: ${STP_ENV}" 

        

        

