name: ENC ENV Variables
on: push
env:
  WF_ENV2: ${{ secrets.WF_ENV }}

jobs:
  enc-log-env:
    env:
      JOB_ENV2: Only avaliable to log-env-jobs
    runs-on: ubuntu-latest
    steps:
    - name: Enc  Log Env Variables
      env:
        STP_ENV2: Only avaliable to Log Env Variables steps
      run: |
        echo "WF_ENV2: ${WF_ENV2}" 
        echo "JOB_ENV2: ${JOB_ENV2}" 
        echo "STP_ENV2: ${STP_ENV2}" 
        
    - name: Enc Log Env Variables 2      
      run: |
        echo "WF_ENV2: ${WF_ENV2}" 
        echo "JOB_ENV2: ${JOB_ENV2}" 
        echo "STP_ENV2: ${STP_ENV2}" 
  
  enc-log-default-env:
    runs-on: ubuntu-latest
    steps:
    - name: Default env variables
      run: |
        echo "HOME: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTION: ${GITHUB_ACTION}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "WF_ENV2: ${WF_ENV2}" 
        echo "JOB_ENV2: ${JOB_ENV2}" 
        echo "STP_ENV2: ${STP_ENV2}" 

        

        

